[package]
name = "rink-data-compiler"
version = "0.6.2"
edition = "2021"

[dependencies]
glob = "0.3"
kdl = "3.0.0"
bincode = "1"
thiserror = "1"
eyre = "0.6"
displaydoc = "0.2"
indexmap = "1.8"

rink-format = { version = "0.6.2", path = "../format" }
